## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "TEKin Vihreät"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "TEKin Vihreät rakentavat kestävämpää teknologiaa ja yhteiskuntaa"
  logo = "images/vihreat_maapallo.jpg"
  favicon = true

# [Params.social]
#   github = "https://github.com/caressofsteel/"
#   twitter = "https://twitter.com/caressofsteel_"
#   email = "caressofsteel@protonmail.com"
#   instagram = "https://instagram.com"
#   linkedin = "https://linkedin.com"
#   telegram = "https://telegram.org"